"""Reusable application settings."""

EMBEDDING_MODEL = "all-MiniLM-L6-v2"
CHUNK_SIZE = 400
CHUNK_OVERLAP = 60
TOP_K = 5
MIN_SIMILARITY_SCORE = 0.20
MIN_KEYWORD_OVERLAP = 1
SECTION_QUERY_MAX_WORDS = 6
EMBEDDING_BATCH_SIZE = 64
